### ISSUE TITLE
Add RSS feed to blog

### ISSUE THREAD

**Issue by xuhcc** [vcmi/VCMI.eu#32]
https://vcmi.eu/blog/

In the old version of website there was an RSS feed, but now it's gone.

**Comment by dydzio0614** [comment]
RSS is kinda relic of the past, but if it can be easily added by @Laserlicht then why not

**Comment by xuhcc** [comment]
>RSS is kinda relic of the past

Not at all. How else could people be notified about new posts?

**Comment by IvanSavenko** [comment]
Looks like Github provides Atom feed:
https://github.com/vcmi/vcmi/releases.atom

**Comment by Laserlicht** [comment]
Will add RSS: https://squidfunk.github.io/mkdocs-material/setup/setting-up-a-blog/#rss

**Comment by xuhcc** [comment]
Thank you.
